### ISSUE TITLE
Caractères accentués incompatibles avec les scripts autohotkey

### ISSUE THREAD

**Issue by BeardJesus** [SaltyYuki/kfee#1]
Bonjour,
Pourrais-tu s'il te plaît transformer tout les caractères accentués en leur version normales?
Cela résoudra le problème de caractères erronés lors de l'utilisation de notre script AHK.
Merci d'avance

**Comment by SaltyYuki** [comment]
Fait dans le commit https://github.com/SaltyYuki/kfee/commit/5e68ebfe95416656e636c9f517d8770ddd146971
