### ISSUE TITLE
Probleme ligne multiple

### ISSUE THREAD

**Issue by BeardJesus** [SaltyYuki/kfee#2]
https://github.com/SaltyYuki/kfee/commit/1a3bc6101795d145c70b5d9bb0afa4f1e9657a96
Sur cette release j'ai besoin que la texte récupéré soit sur une seule ligne car AutoHotKey nécessite que ces lignes de code soient bien formatées 

"Send Kfee des jeux : vendredi 31 mai 2019 (aujourd'hui) a midi - Pas de plat du jour ! 
Maxi-entrees et desserts uniquement ! {enter}"

La deuxième ligne n'est pas interprétable. Pourrais-tu s'il te plaît faire en sorte de remove tout les retours a la ligne?
Merci d'avance

**Comment by SaltyYuki** [comment]
Corrigé dans https://github.com/SaltyYuki/kfee/commit/7a57e5750845187291d530a5a9db403a57ccdc23

**Comment by BeardJesus** [comment]
Ce n'est pas résolu voici le résultat obtenu : 
"Send Kfee des jeux : vendredi 31 mai 2019 (aujourd'hui) a midi - Pas de plat du jour !
Maxi-entrees et desserts uniquement ! {enter}"
En ayant modifié sous ta supervision la ligne par : 
"    $plat = $plat.replace("wb_sunny", "").replace("`r|`n", " ")"

**Comment by BeardJesus** [comment]
Les backquote ont disparues dans mon commentaire du dessus mais il y en a une avant le r et une avant le n

**Comment by SaltyYuki** [comment]
Corrigé https://github.com/SaltyYuki/kfee/commit/6a307241b1da2b6bfb5366d8393a0c4adf87a267
