### ISSUE TITLE
Gérer une autre ligne a modifier

### ISSUE THREAD

**Issue by BeardJesus** [SaltyYuki/kfee#3]
Bonjour,
Pourrais-tu stp prendre en charge la ligne du Hambourgeois en indiquant : 
- Hambourgeois ( tous les jours de la semaine sauf le lundi )
et
- Hambourgeois : Fermé (uniquement le lundi)
Un peu a l'instar de ce qui est fait actuellement pour le kfee stp?
Merci d'avance

PS : N'hésite pas a me demander si tu as besoin du script AHK pour avoir un fichier destination pour tes tests.
Cordialement

**Comment by SaltyYuki** [comment]
Hello, Fait dans https://github.com/SaltyYuki/kfee/commit/13389fb5cd45ab4f8ca816644202422a3497f27c + refonte du script pour rajouter plus facilement la gestion de plusieurs ligne
